import Head from 'next/head'
import { useEffect } from 'react'
import { useRouter } from 'next/router'

import useUser, { STATES } from 'hooks/useUser'

import { loginWithGithub } from 'firebase/client'

import Button from 'components/Button'
import GitHub from 'components/Icons/Github'

const Home = () => {
  const user = useUser()
  const router = useRouter()

  useEffect(() => {
    user && router.replace('/home')
  }, [user])

  const handleLoginGithub = () => {
    loginWithGithub()
      .catch(err => {
        console.error(err)
      })
  }

  return <>
    <Head>
      <title>devchat - Iniciar sesión</title>
      <meta name='description' content='Generated by create next app' />
      <meta name='viewport' content='width=device-width, initial-scale=1' />
      <link rel='icon' href='/favicon.svg' />
    </Head>
    {user === STATES.NOT_LOGGED && (
      <Button onClick={handleLoginGithub}>
        <GitHub fill='#fff' width={24} height={24} />
        Iniciar sesión con Github
      </Button>
    )}
  </>
}

export default Home