import Head from 'next/head'

const Home = () => {
  return <>
      <Head>
        <title>devchat - Iniciar sesión</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.svg' />
      </Head>
    </>
}

export default Home